server:
  port: 8080
  servlet:
    context-path: /

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  http:
    encoding:
      charset: utf-8


